### ISSUE TITLE
Issue with the User Auth Api 

### ISSUE THREAD

**Issue by 360Parminder** [BearerOP/TheSlugProject#14]
Api sending response status 200 on wrong Password
<img width="297" alt="Screenshot 2024-09-13 at 1 08 28 PM" src="https://github.com/user-attachments/assets/e5302614-891d-45cd-b017-bbed2468e381">
<img width="467" alt="Screenshot 2024-09-13 at 1 09 27 PM" src="https://github.com/user-attachments/assets/88769141-a295-40d9-ac9a-ac9602821e34">

**Comment by BearerOP** [comment]
Solved issue with #15 pr
